name: cronomaster
base: core22
version: "2.0.0"
license: MIT
summary: A simple Python GTK time wallet using seconds sending
description: |
  This use time counting and bytes files to storage seconds
  with TCP/IP protocol could sends number to another IP 
  and port device that is running the program using 
  socket module for it in a GTK window for give value
  and make sendable the time.

confinement: strict

platforms:
  amd64:
  
parts:
  cronomaster:
    plugin: python
    source-type: git
    source: https://github.com/martina-pauer/cronomaster
    
    override-build: |
      folder=/root/prime
      cp -R * $folder
      chmod -R 755 $folder/src/graphics/cronomaster_gtk.py
    
    build-packages:
      - python3-dev
      - python3-gi
      - python3-gi-cairo
      - libgirepository1.0-dev # For PyGObject/GTK3 bindings
      - gir1.2-gtk-3.0
    stage-packages:
      - python3-gi
      - python3-dev
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libgirepository1.0-dev # For PyGObject/GTK3 bindings      
      - adwaita-icon-theme # Common GTK theme 
               
apps:
  cronomaster:
    command: ./src/graphics/cronomaster_gtk.py